[[item]]
"Name" = '''Cirq [@cirq]'''
"Language" = '''python'''
"Hardware" = '''Yes'''
"Multi-platform" = '''No'''
"Built-in applications" = '''Chemistry, ML, Noise characterization, Optimization'''
[[item]]
"Name" = '''DQCSim [@DQCSim]'''
"Language" = '''python, C++, Rust'''
"Hardware" = '''No'''
"Multi-platform" = '''No'''
"Built-in applications" = '''--'''
[[item]]
"Name" = '''IQS [@intel]'''
"Language" = '''C++'''
"Hardware" = '''No'''
"Multi-platform" = '''No'''
"Built-in applications" = '''QAOA'''
[[item]]
"Name" = '''$|Lib\rangle $[@Lib]'''
"Language" = '''python, C++'''
"Hardware" = '''Yes**'''
"Multi-platform" = '''Yes'''
"Built-in applications" = '''--'''
[[item]]
"Name" = '''Pennylane [@pennylane]'''
"Language" = '''python'''
"Hardware" = '''Yes**'''
"Multi-platform" = '''Yes'''
"Built-in applications" = '''ML, Optimization'''
[[item]]
"Name" = '''ProjectQ [@projectq]'''
"Language" = '''python'''
"Hardware" = '''Yes**'''
"Multi-platform" = '''Yes'''
"Built-in applications" = '''Fermionic simulation, Optimization'''
[[item]]
"Name" = '''pyquil/Forest [@pyquil]'''
"Language" = '''python, Lisp'''
"Hardware" = '''Yes'''
"Multi-platform" = '''No'''
"Built-in applications" = '''VQE, QAOA, Noise characterization, Optimization'''
[[item]]
"Name" = '''QDK [@qsharp]'''
"Language" = '''python, C#,  Q#'''
"Hardware" = '''Yes**'''
"Multi-platform" = '''No'''
"Built-in applications" = '''Chemistry, Optimization'''
[[item]]
"Name" = '''Qibo [@qibo]'''
"Language" = '''python'''
"Hardware" = '''Yes*'''
"Multi-platform" = '''Yes'''
"Built-in applications" = '''VQE, QAOA, Adiabatic evolution, Optimization'''
[[item]]
"Name" = '''Qiskit [@Qiskit]'''
"Language" = '''python'''
"Hardware" = '''Yes'''
"Multi-platform" = '''No'''
"Built-in applications" = '''Chemistry, ML, Optimization, Finance, Noise characterization'''
[[item]]
"Name" = '''QTensor [@QTensor]'''
"Language" = '''python, C++'''
"Hardware" = '''No'''
"Multi-platform" = '''No'''
"Built-in applications" = '''Tensor-Network simulator, quantum circuit simulator, QAOA'''
[[item]]
"Name" = '''QuEST [@quest,jones2020questlink]'''
"Language" = '''C++, Mathematica'''
"Hardware" = '''No'''
"Multi-platform" = '''Yes'''
"Built-in applications" = '''--'''
[[item]]
"Name" = '''Quimb [@quimb]'''
"Language" = '''python'''
"Hardware" = '''No'''
"Multi-platform" = '''No'''
"Built-in applications" = '''Tensor-Network simulator, quantum circuit simulator'''
[[item]]
"Name" = '''Qulacs [@qulacs]'''
"Language" = '''python, C++'''
"Hardware" = '''No'''
"Multi-platform" = '''No'''
"Built-in applications" = '''Simulator, noise characterization'''
[[item]]
"Name" = '''StrawberryFields [@strawberry]'''
"Language" = '''python'''
"Hardware" = '''Yes*'''
"Multi-platform" = '''No'''
"Built-in applications" = '''GBS'''
[[item]]
"Name" = '''Tequila [@tequila]'''
"Language" = '''python'''
"Hardware" = '''Yes**'''
"Multi-platform" = '''Yes'''
"Built-in applications" = '''Chemistry, ML, Noise characterization, Optimization'''
[[item]]
"Name" = '''XACC [@xacc]'''
"Language" = '''python, C++'''
"Hardware" = '''Yes**'''
"Multi-platform" = '''Yes'''
"Built-in applications" = '''Optimization, VQE, QAOA, RBM and other algorithms'''
[[item]]
"Name" = '''Yao [@yao]'''
"Language" = '''Julia'''
"Hardware" = '''No'''
"Multi-platform" = '''No'''
"Built-in applications" = '''--'''